#!bin/bash


if [[ -f "secrets.sh" ]]; then
    source "$(realpath "$0" | sed 's|\(.*\)/.*|\1|')/secrets.sh"
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
    sudo apt install gh
    echo ${{ $gitTokenFile }} | gh auth login --with-token
    git config --global "$gitEmail"
    git config --global "$gitUser"
    git config --global init.defaultBranch "main"
    ssh-keygen -o -t rsa -C "$gitEmail"
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_rsa.pub
    gh ssh-key add ~/.ssh/id_rsa.pub

    # Make file executable
    chmod u+x manager

    # Adds manager to PATH
    echo "export PATH=$PATH:$PWD" >> ~/.bashrc

    # Loads PATH
    source ~/.bashrc
else
    echo "There is no secrets files. Please add you information in order to complete setup"

fi