#!bin/bash


if [[ -f "secrets.sh"]]; then
    source "$(realpath "$0" | sed 's|\(.*\)/.*|\1|')/secrets.sh"
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
    sudo apt install gh
    gh auth login --with-token < $gitTokenFile
    
    ssh-keygen -t ed25519 -C "$gitEmail"
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_ed25519
    gh ssh-key add ~/.ssh/id_ed25519

    # Make file executable
    chmod u+x manager

    # Adds manager to PATH
    echo "export PATH=$PATH:$PWD" >> ~/.bashrc

    # Loads PATH
    source ~/.bashrc
else
    echo "There is no secrets files. Please add you information in order to complete setup"
fi